// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mudjpgmdwcminjllkgab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZGpwZ21kd2NtaW5qbGxrZ2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTQ3NDMsImV4cCI6MjA2ODk5MDc0M30.WExLPE8Zic2SxTkdFu6erE3EYeKNv-0VcifyM9PN984";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});